name: catandball
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - numpy
  - pillow
  - matplotlib
  - pandas
  - scipy
  - pip
  - pip:
      - transformers==4.52.4
      - ultralytics==8.3.157
      - huggingface-hub==0.33.0
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - requests==2.32.4
      - python-dotenv==1.1.0
      - onnx==1.17.0
      - onnxruntime==1.22.0
      - black==25.1.0
      - ruff==0.11.13
      - poetry==2.1.3
      - debugpy==1.8.14
      - packaging==25.0
      - pyright==1.1.401
      - rich==14.0.0
      - virtualenv==20.31.2
      - yarl==1.20.0
      - zstandard==0.23.0
